AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy a TaskSet

Parameters: 
  ECSCluster:
    Type: String
    Default: blue-green
    AllowedValues: 
      - blue-green
      - blue-green1
      - blue-green2
  ECSService:
    Type: String
    Default: bg-svc-example
    AllowedValues: 
      - bg-svc-example
      - bg-svc-example1
      - bg-svc-example2
  TaskDefinition:
    Type: String
    AllowedValues: 
      - BlueTaskDefinition
      - GreenTaskDefinition
  ServiceTargetGroup:
    Type: String
    AllowedValues:
      - arn:aws:elasticloadbalancing:us-east-1:111122223333:targetgroup/exter-BlueS-1UB69WFT25317/a3e2e23672a63ec2
      - arn:aws:elasticloadbalancing:us-east-1:111122223333:targetgroup/exter-Green-1ADL07GUB01SA/e36ad71e096c7234
  ServiceSecurityGroup:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Default: sg-111122223333
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Select at two subnets in your selected VPC.  


Resources:
  TaskSet:
    Type: AWS::ECS::TaskSet
    Properties:
      Cluster: !Ref ECSCluster
      Service: !Ref ECSService
      Scale:
        Unit: PERCENT
        Value: 100
      TaskDefinition: !Ref TaskDefinition
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: nginx
          ContainerPort: 80
          TargetGroupArn: !Ref ServiceTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:   !Ref ServiceSecurityGroup
          Subnets: !Ref Subnets
